PlantillaMvcNetCore/Models/Departamento.cs
namespace PlantillaMvcNetCore.Models {
    public class Departamento {

        public int DeptNo { get; set; }
        public string Nombre { get; set; }
        public string Localizacion { get; set; }

    }
}

PlantillaMvcNetCore/Models/Doctor.cs
namespace PlantillaMvcNetCore.Models {
    public class Doctor {

        public string HospitalCod { get; set; }
        public string DoctorNo { get; set; }
        public string Apellido { get; set; }
        public string Especialidad { get; set; }
        public int Salario { get; set; }

    }
}

PlantillaMvcNetCore/Models/Empleado.cs
namespace PlantillaMvcNetCore.Models {
    public class Empleado {

        public int EmpNo { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Dir { get; set; }
        public DateTime FechaAlta { get; set; }
        public int Salario { get; set; }
        public int Comision { get; set; }
        public int DeptNo { get; set; }

    }
}

PlantillaMvcNetCore/Models/Enfermo.cs
namespace PlantillaMvcNetCore.Models {
    public class Enfermo {

        public string Inscripcion { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaAlta { get; set; }
        public string Sexo { get; set; }
        public string NSS { get; set; }

    }
}

PlantillaMvcNetCore/Models/Hospital.cs
namespace PlantillaMvcNetCore.Models {
    public class Hospital {

        public int HospitalCod { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int NumCama { get; set; }

    }
}

PlantillaMvcNetCore/Models/Ocupacion.cs
namespace PlantillaMvcNetCore.Models {
    public class Ocupacion {

        public int Inscripcion { get; set; }
        public int HospitalCod { get; set; }
        public int SalaCod { get; set; }
        public int Cama { get; set; }

    }
}

PlantillaMvcNetCore/Models/Plantilla.cs
namespace PlantillaMvcNetCore.Models {
    public class Plantilla {

        public int HospitalCod { get; set; }
        public int SalaCod { get; set; }
        public int EmpleadoNo { get; set; }
        public string Apellido { get; set; }
        public string Funcion { get; set; }
        public string Turno { get; set; }
        public int Salario { get; set; }

    }
}

PlantillaMvcNetCore/Models/Sala.cs
namespace PlantillaMvcNetCore.Models {
    public class Sala {

        public int HospitalCod { get; set; }
        public int SalaCod { get; set; }
        public string Nombre { get; set; }
        public int NumCama { get; set; }

    }
}

PlantillaMvcNetCore/Controllers/HospitalesController.cs
using Microsoft.AspNetCore.Mvc;
using PlantillaMvcNetCore.Models;
using PlantillaMvcNetCore.Repositories;
using PlantillaMvcNetCore.Tools;

namespace PlantillaMvcNetCore.Controllers {
    public class HospitalesController : Controller {

        IRepositoryHospitales repo;
        IHospitalTools tools;

        public HospitalesController(IRepositoryHospitales repo, IHospitalTools tools) {
            this.repo = repo;
            this.tools = tools;
        }

        public IActionResult ShowHospitales() {
            List<Hospital> hospitales = this.repo.GetHospitales();
            return View(hospitales);
        }

        public IActionResult Details(int hospital_cod) {
            Hospital hospital = this.repo.FindHospital(hospital_cod);
            return View(hospital);
        }

        [HttpGet]
        public IActionResult Insert() {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(Hospital hospital) {
            this.repo.InsertHospital(hospital);
            return RedirectToAction("ShowHospitales");
        }        
        
        [HttpGet]
        public IActionResult Update(int hospital_cod) {
            Hospital hospital = this.repo.FindHospital(hospital_cod);
            return View(hospital);
        }

        [HttpPost]
        public IActionResult Update(Hospital hospital) {
            this.repo.UpdateHospital(hospital);
            return RedirectToAction("ShowHospitales");
        }        
        
        [HttpGet]
        public IActionResult Delete(int hospital_cod) {
            this.repo.DeleteHospital(hospital_cod);
            return RedirectToAction("ShowHospitales");
        }

        public IActionResult Others() {
            ViewData["MAX_HOSPITAL"] = this.tools.GetMaximoHospital();
            return View();
        }

    }
}

PlantillaMvcNetCore/Views/Hospitales/Details.cshtml
@model Hospital

<h1 style="text-align: center;" class="text-info">
    Detalles Hospitales
</h1>

<dl>
    <dt>@Model.Nombre - @Model.HospitalCod</dt>
    <dd>@Model.Direccion</dd>

    <dt>Teléfono:</dt>
    <dd>@Model.Telefono</dd>

    <dt>Camas:</dt>
    <dd>@Model.NumCama</dd>
</dl>

@Html.ActionLink("Volver", "ShowHospitales", "Hospitales", null, 
                 new { @class = "btn btn-secondary", style = "font-weight: bold;"})

PlantillaMvcNetCore/Views/Hospitales/Insert.cshtml
<h1 style="text-align: center;" class="text-success">
    Insert Hospital
</h1>

<form method="post">
    <input type="hidden" class="form-control" name="hospitalcod"/>

    <label class="form-label mt-3">Nombre</label>
    <input type="text" class="form-control" name="nombre" required/>

    <label class="form-label mt-3">Dirección</label>
    <input type="text" class="form-control" name="direccion" required/>

    <label class="form-label mt-3">Teléfono</label>
    <input type="text" class="form-control" name="telefono" required/>

    <label class="form-label mt-3">Número de camas</label>
    <input type="text" class="form-control" name="numcama" required/>

    <button class="btn btn-success w-100 my-3">
        Insert
    </button>
</form>

@Html.ActionLink("Volver", "ShowHospitales", "Hospitales", null,
                 new { @class = "btn btn-secondary", style = "font-weight: bold;"})

PlantillaMvcNetCore/Views/Hospitales/Others.cshtml
@{
    int maximoHospital = int.Parse(ViewData["MAX_HOSPITAL"].ToString());
}

<table class="table table-dark table-bordered" style="text-align: center;">
    <thead>
        <tr>
            <th>
                Others
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                El siguiente máximo de hospital es: @maximoHospital
            </td>
        </tr>
    </tbody>
</table>

@Html.ActionLink("Volver", "ShowHospitales", "Hospitales", null, new { @class = "btn btn-outline-secondary" })

PlantillaMvcNetCore/Views/Hospitales/ShowHospitales.cshtml
@model List<Hospital>

@{
    ViewData["Title"] = "Hospitales";
}

<h1 style="text-align: center;" class="text-primary">
    Hospitales
</h1>

<table class="table table-dark table-bordered">
    <thead>
        <tr style="text-align: center;">
            <th>Código</th>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th>Nº Camas</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Hospital hosp in Model) {
            <tr>
                <td style="text-align: center;">@hosp.HospitalCod</td>
                <td>@hosp.Nombre</td>
                <td>@hosp.Direccion</td>
                <td>@hosp.Telefono</td>
                <td>@hosp.NumCama</td>
                <td style="text-align: center;">
                    @Html.ActionLink("Detalles", "Details", "Hospitales", new { hospital_cod = hosp.HospitalCod }, 
                                     new { @class = "btn btn-primary", style = "font-weight: bold;"})

                    @Html.ActionLink("Update", "Update", "Hospitales", new { hospital_cod = hosp.HospitalCod }, 
                                     new { @class = "btn btn-warning", style = "font-weight: bold;"})
                    
                    @Html.ActionLink("Delete", "Delete", "Hospitales", new { hospital_cod = hosp.HospitalCod }, 
                                     new { @class = "btn btn-danger", style = "font-weight: bold;"})
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.ActionLink("Create Hospital", "Insert", "Hospitales", null, new { @class = "btn btn-primary", style = "font-weight: bold;"})

PlantillaMvcNetCore/Views/Hospitales/Update.cshtml
@model Hospital

<h1 style="text-align: center;" class="text-warning">
    Update Hospital
</h1>

<form method="post">
    <input type="number" value="@Model.HospitalCod" class="form-control" name="hospitalcod" disabled/>

    <label class="form-label mt-3">Nombre</label>
    <input type="text" value="@Model.Nombre" class="form-control" name="nombre" required/>

    <label class="form-label mt-3">Dirección</label>
    <input type="text" value="@Model.Direccion" class="form-control" name="direccion" required/>

    <label class="form-label mt-3">Teléfono</label>
    <input type="text" value="@Model.Telefono" class="form-control" name="telefono" required/>
    
    <label class="form-label mt-3">Número de camas</label>
    <input type="text" value="@Model.NumCama" class="form-control" name="numcama" required/>

    <button class="btn btn-warning w-100 my-3">
        Update
    </button>
</form>

@Html.ActionLink("Volver", "ShowHospitales", "Hospitales", null,
                 new { @class = "btn btn-secondary", style = "font-weight: bold;"})

PlantillaMvcNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlantillaMvcNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlantillaMvcNetCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Hospital" asp-action="Index">PlantillaMvcNetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hospitales" asp-action="ShowHospitales">Hospitales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hospitales" asp-action="Others">Others</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PlantillaMvcNetCore - <a asp-area="" asp-controller="Hospital" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>